# Generated by Django 2.1.4 on 2019-11-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstuff',
            name='cal10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='foodstuff',
            name='cal100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='foodstuff',
            name='cal50',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
